version: "{build}"
os: Windows Server 2016
init:
  - cmd: set PATH=C:\MinGW\bin;%PATH%
  - cmd: copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
install:
  - curl -fsSL -o C:\wix310-binaries.zip http://static.wixtoolset.org/releases/v3.10.3.3007/wix310-binaries.zip
  - 7z x C:\wix310-binaries.zip -y -r -oC:\wix310
  - set PATH=C:\wix310;%PATH%
  # TODO: Create MSI for Vale Server.
  #
  # See https://github.com/cloose/CuteMarkEd/blob/develop/CuteMarkEd.wxs
  - curl -fsSL -o C:\go-msi.msi https://github.com/mh-cbon/go-msi/releases/download/1.0.1/go-msi-amd64.msi
  - msiexec.exe /i C:\go-msi.msi /quiet
  - set PATH=C:\Program Files\go-msi\;%PATH%
