openapi: 3.0.2

servers:
  - url: http://127.0.0.1:7777

tags:
  - name: Linting and Suggestions
    description: Find errors and receive possible solutions
  - name: Local Resources
    description: Get information about the active project and local Vale resources

externalDocs:
  description: Vale Server user documentation
  url: https://docs.errata.ai/vale-server/install

components:
  schemas:
    Suggestions:
      type: array
      items:
        type:
          string
    Action:
      type: object
      required:
        - Name
        - Params
      properties:
        Name:
          type: string
        Params:
          type: array
          items:
            type: string
    Alert:
      type: object
      required:
        - Action
        - Check
        - Description
        - Line
        - Link
        - Message
        - Severity
        - Span
        - Match
      properties:
        Action:
          $ref: "#/components/schemas/Action"
        Check:
          type: string
        Description:
          type: string
        Line:
          type: integer
        Link:
          type: string
        Message:
          type: string
        Severity:
          type: string
        Span:
          type: array
          items:
            type: string
        Match:
          type: string
    Alerts:
      type: array
      items:
        $ref: "#/components/schemas/Alert"
